version: '3.6'

services:
  api:
    container_name: pi-backend
    build:
      dockerfile: Dockerfile
      context: .
      target: development
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      # strictly for hot reloading
      - .:/usr/src/app
    env_file:
      - .env
    command: [ "sh", "-c", "yarn start:dev" ]
    ports:
      - '4000:4000'

  postgres:
    image: postgres:15.3-bookworm
    container_name: postgres
    restart: always
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - '5432:${DATABASE_PORT}'
    env_file:
      - .env
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U ${DATABASE_USERNAME} -d ${DATABASE_NAME}"
        ]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
